### PR TITLE
Joel

### PR DESCRIPTION
**Pull request by ghost**
This fixes some bugs in the map and it adds Junit tests for the map

### CODE REVIEW

**Comment by yeyyosing** [comment]
This has JUnit tests for the deserialization code, however, I don't know how to load a JsonObject without hard coding it in.

**Comment by derekargueta** [comment]
Why is the Gson JAR deleted?

**Comment by yeyyosing** [comment]
Because i had downloaded that jar file without realizing that it was in the lib folder already.

**Comment by yeyyosing** [comment]
All my JUnit tests works

**Pull request merged**
